/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientTermsRouteImport } from './routes/patient.terms'
import { Route as PatientSubscriptionRouteImport } from './routes/patient.subscription'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientNetworkRouteImport } from './routes/patient.network'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientInviteTokenRouteImport } from './routes/patient-invite.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTenantRouteImport } from './routes/app.$tenant'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppTenantIndexRouteImport } from './routes/app.$tenant.index'
import { Route as AppTenantValidateRouteImport } from './routes/app.$tenant.validate'
import { Route as AppTenantStaffRouteImport } from './routes/app.$tenant.staff'
import { Route as AppTenantSettingsRouteImport } from './routes/app.$tenant.settings'
import { Route as AppTenantServicesRouteImport } from './routes/app.$tenant.services'
import { Route as AppTenantPatientsRouteImport } from './routes/app.$tenant.patients'
import { Route as AppTenantFinanceRouteImport } from './routes/app.$tenant.finance'
import { Route as AppTenantExecutionsRouteImport } from './routes/app.$tenant.executions'
import { Route as AppTenantContractsRouteImport } from './routes/app.$tenant.contracts'
import { Route as AppTenantBillingRouteImport } from './routes/app.$tenant.billing'
import { Route as AppTenantPatientsPatientIdRouteImport } from './routes/app.$tenant.patients.$patientId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientTermsRoute = PatientTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSubscriptionRoute = PatientSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNetworkRoute = PatientNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientInviteTokenRoute = PatientInviteTokenRouteImport.update({
  id: '/patient-invite/$token',
  path: '/patient-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantRoute = AppTenantRouteImport.update({
  id: '/app/$tenant',
  path: '/app/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTenantIndexRoute = AppTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantValidateRoute = AppTenantValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantStaffRoute = AppTenantStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantSettingsRoute = AppTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantServicesRoute = AppTenantServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantPatientsRoute = AppTenantPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantFinanceRoute = AppTenantFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantExecutionsRoute = AppTenantExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantContractsRoute = AppTenantContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantBillingRoute = AppTenantBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantPatientsPatientIdRoute =
  AppTenantPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AppTenantPatientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRouteWithChildren
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/$tenant': typeof AppTenantRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/patient-invite/$token': typeof PatientInviteTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/network': typeof PatientNetworkRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/subscription': typeof PatientSubscriptionRoute
  '/patient/terms': typeof PatientTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/app/$tenant/billing': typeof AppTenantBillingRoute
  '/app/$tenant/contracts': typeof AppTenantContractsRoute
  '/app/$tenant/executions': typeof AppTenantExecutionsRoute
  '/app/$tenant/finance': typeof AppTenantFinanceRoute
  '/app/$tenant/patients': typeof AppTenantPatientsRouteWithChildren
  '/app/$tenant/services': typeof AppTenantServicesRoute
  '/app/$tenant/settings': typeof AppTenantSettingsRoute
  '/app/$tenant/staff': typeof AppTenantStaffRoute
  '/app/$tenant/validate': typeof AppTenantValidateRoute
  '/app/$tenant/': typeof AppTenantIndexRoute
  '/app/$tenant/patients/$patientId': typeof AppTenantPatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/onboarding': typeof OnboardingRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/patient-invite/$token': typeof PatientInviteTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/network': typeof PatientNetworkRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/subscription': typeof PatientSubscriptionRoute
  '/patient/terms': typeof PatientTermsRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
  '/app/$tenant/billing': typeof AppTenantBillingRoute
  '/app/$tenant/contracts': typeof AppTenantContractsRoute
  '/app/$tenant/executions': typeof AppTenantExecutionsRoute
  '/app/$tenant/finance': typeof AppTenantFinanceRoute
  '/app/$tenant/patients': typeof AppTenantPatientsRouteWithChildren
  '/app/$tenant/services': typeof AppTenantServicesRoute
  '/app/$tenant/settings': typeof AppTenantSettingsRoute
  '/app/$tenant/staff': typeof AppTenantStaffRoute
  '/app/$tenant/validate': typeof AppTenantValidateRoute
  '/app/$tenant': typeof AppTenantIndexRoute
  '/app/$tenant/patients/$patientId': typeof AppTenantPatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRouteWithChildren
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/$tenant': typeof AppTenantRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/patient-invite/$token': typeof PatientInviteTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/network': typeof PatientNetworkRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/subscription': typeof PatientSubscriptionRoute
  '/patient/terms': typeof PatientTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/app/$tenant/billing': typeof AppTenantBillingRoute
  '/app/$tenant/contracts': typeof AppTenantContractsRoute
  '/app/$tenant/executions': typeof AppTenantExecutionsRoute
  '/app/$tenant/finance': typeof AppTenantFinanceRoute
  '/app/$tenant/patients': typeof AppTenantPatientsRouteWithChildren
  '/app/$tenant/services': typeof AppTenantServicesRoute
  '/app/$tenant/settings': typeof AppTenantSettingsRoute
  '/app/$tenant/staff': typeof AppTenantStaffRoute
  '/app/$tenant/validate': typeof AppTenantValidateRoute
  '/app/$tenant/': typeof AppTenantIndexRoute
  '/app/$tenant/patients/$patientId': typeof AppTenantPatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/onboarding'
    | '/patient'
    | '/planos'
    | '/privacidade'
    | '/termos'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/metrics'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/$tenant'
    | '/auth/callback'
    | '/invite/$token'
    | '/patient-invite/$token'
    | '/patient/history'
    | '/patient/network'
    | '/patient/profile'
    | '/patient/subscription'
    | '/patient/terms'
    | '/admin/'
    | '/patient/'
    | '/app/$tenant/billing'
    | '/app/$tenant/contracts'
    | '/app/$tenant/executions'
    | '/app/$tenant/finance'
    | '/app/$tenant/patients'
    | '/app/$tenant/services'
    | '/app/$tenant/settings'
    | '/app/$tenant/staff'
    | '/app/$tenant/validate'
    | '/app/$tenant/'
    | '/app/$tenant/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/onboarding'
    | '/planos'
    | '/privacidade'
    | '/termos'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/metrics'
    | '/admin/settings'
    | '/admin/tenants'
    | '/auth/callback'
    | '/invite/$token'
    | '/patient-invite/$token'
    | '/patient/history'
    | '/patient/network'
    | '/patient/profile'
    | '/patient/subscription'
    | '/patient/terms'
    | '/admin'
    | '/patient'
    | '/app/$tenant/billing'
    | '/app/$tenant/contracts'
    | '/app/$tenant/executions'
    | '/app/$tenant/finance'
    | '/app/$tenant/patients'
    | '/app/$tenant/services'
    | '/app/$tenant/settings'
    | '/app/$tenant/staff'
    | '/app/$tenant/validate'
    | '/app/$tenant'
    | '/app/$tenant/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/contato'
    | '/onboarding'
    | '/patient'
    | '/planos'
    | '/privacidade'
    | '/termos'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/metrics'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/$tenant'
    | '/auth/callback'
    | '/invite/$token'
    | '/patient-invite/$token'
    | '/patient/history'
    | '/patient/network'
    | '/patient/profile'
    | '/patient/subscription'
    | '/patient/terms'
    | '/admin/'
    | '/patient/'
    | '/app/$tenant/billing'
    | '/app/$tenant/contracts'
    | '/app/$tenant/executions'
    | '/app/$tenant/finance'
    | '/app/$tenant/patients'
    | '/app/$tenant/services'
    | '/app/$tenant/settings'
    | '/app/$tenant/staff'
    | '/app/$tenant/validate'
    | '/app/$tenant/'
    | '/app/$tenant/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  OnboardingRoute: typeof OnboardingRoute
  PatientRoute: typeof PatientRouteWithChildren
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AppTenantRoute: typeof AppTenantRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PatientInviteTokenRoute: typeof PatientInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/terms': {
      id: '/patient/terms'
      path: '/terms'
      fullPath: '/patient/terms'
      preLoaderRoute: typeof PatientTermsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/subscription': {
      id: '/patient/subscription'
      path: '/subscription'
      fullPath: '/patient/subscription'
      preLoaderRoute: typeof PatientSubscriptionRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/network': {
      id: '/patient/network'
      path: '/network'
      fullPath: '/patient/network'
      preLoaderRoute: typeof PatientNetworkRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient-invite/$token': {
      id: '/patient-invite/$token'
      path: '/patient-invite/$token'
      fullPath: '/patient-invite/$token'
      preLoaderRoute: typeof PatientInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$tenant': {
      id: '/app/$tenant'
      path: '/app/$tenant'
      fullPath: '/app/$tenant'
      preLoaderRoute: typeof AppTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/$tenant/': {
      id: '/app/$tenant/'
      path: '/'
      fullPath: '/app/$tenant/'
      preLoaderRoute: typeof AppTenantIndexRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/validate': {
      id: '/app/$tenant/validate'
      path: '/validate'
      fullPath: '/app/$tenant/validate'
      preLoaderRoute: typeof AppTenantValidateRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/staff': {
      id: '/app/$tenant/staff'
      path: '/staff'
      fullPath: '/app/$tenant/staff'
      preLoaderRoute: typeof AppTenantStaffRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/settings': {
      id: '/app/$tenant/settings'
      path: '/settings'
      fullPath: '/app/$tenant/settings'
      preLoaderRoute: typeof AppTenantSettingsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/services': {
      id: '/app/$tenant/services'
      path: '/services'
      fullPath: '/app/$tenant/services'
      preLoaderRoute: typeof AppTenantServicesRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/patients': {
      id: '/app/$tenant/patients'
      path: '/patients'
      fullPath: '/app/$tenant/patients'
      preLoaderRoute: typeof AppTenantPatientsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/finance': {
      id: '/app/$tenant/finance'
      path: '/finance'
      fullPath: '/app/$tenant/finance'
      preLoaderRoute: typeof AppTenantFinanceRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/executions': {
      id: '/app/$tenant/executions'
      path: '/executions'
      fullPath: '/app/$tenant/executions'
      preLoaderRoute: typeof AppTenantExecutionsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/contracts': {
      id: '/app/$tenant/contracts'
      path: '/contracts'
      fullPath: '/app/$tenant/contracts'
      preLoaderRoute: typeof AppTenantContractsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/billing': {
      id: '/app/$tenant/billing'
      path: '/billing'
      fullPath: '/app/$tenant/billing'
      preLoaderRoute: typeof AppTenantBillingRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/patients/$patientId': {
      id: '/app/$tenant/patients/$patientId'
      path: '/$patientId'
      fullPath: '/app/$tenant/patients/$patientId'
      preLoaderRoute: typeof AppTenantPatientsPatientIdRouteImport
      parentRoute: typeof AppTenantPatientsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientNetworkRoute: typeof PatientNetworkRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientSubscriptionRoute: typeof PatientSubscriptionRoute
  PatientTermsRoute: typeof PatientTermsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientHistoryRoute: PatientHistoryRoute,
  PatientNetworkRoute: PatientNetworkRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientSubscriptionRoute: PatientSubscriptionRoute,
  PatientTermsRoute: PatientTermsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface AppTenantPatientsRouteChildren {
  AppTenantPatientsPatientIdRoute: typeof AppTenantPatientsPatientIdRoute
}

const AppTenantPatientsRouteChildren: AppTenantPatientsRouteChildren = {
  AppTenantPatientsPatientIdRoute: AppTenantPatientsPatientIdRoute,
}

const AppTenantPatientsRouteWithChildren =
  AppTenantPatientsRoute._addFileChildren(AppTenantPatientsRouteChildren)

interface AppTenantRouteChildren {
  AppTenantBillingRoute: typeof AppTenantBillingRoute
  AppTenantContractsRoute: typeof AppTenantContractsRoute
  AppTenantExecutionsRoute: typeof AppTenantExecutionsRoute
  AppTenantFinanceRoute: typeof AppTenantFinanceRoute
  AppTenantPatientsRoute: typeof AppTenantPatientsRouteWithChildren
  AppTenantServicesRoute: typeof AppTenantServicesRoute
  AppTenantSettingsRoute: typeof AppTenantSettingsRoute
  AppTenantStaffRoute: typeof AppTenantStaffRoute
  AppTenantValidateRoute: typeof AppTenantValidateRoute
  AppTenantIndexRoute: typeof AppTenantIndexRoute
}

const AppTenantRouteChildren: AppTenantRouteChildren = {
  AppTenantBillingRoute: AppTenantBillingRoute,
  AppTenantContractsRoute: AppTenantContractsRoute,
  AppTenantExecutionsRoute: AppTenantExecutionsRoute,
  AppTenantFinanceRoute: AppTenantFinanceRoute,
  AppTenantPatientsRoute: AppTenantPatientsRouteWithChildren,
  AppTenantServicesRoute: AppTenantServicesRoute,
  AppTenantSettingsRoute: AppTenantSettingsRoute,
  AppTenantStaffRoute: AppTenantStaffRoute,
  AppTenantValidateRoute: AppTenantValidateRoute,
  AppTenantIndexRoute: AppTenantIndexRoute,
}

const AppTenantRouteWithChildren = AppTenantRoute._addFileChildren(
  AppTenantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  OnboardingRoute: OnboardingRoute,
  PatientRoute: PatientRouteWithChildren,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AppTenantRoute: AppTenantRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  PatientInviteTokenRoute: PatientInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
